const router = require('express').Router();
const controller = require('./report.controller');
const { protect } = require('../../middlewares/authMiddleware');
const { permit } = require('../../middlewares/roleMiddleware');
const roles = require('../../constants/roles');
router.use(protect);
router.get('/daily-summary', permit(roles.ADMIN, roles.MANAGER), controller.dailySummary);
router.get('/production', permit(roles.ADMIN, roles.MANAGER), controller.production);
router.get('/pathai', permit(roles.ADMIN, roles.MANAGER), controller.process('PATHAI'));
router.get('/bharai', permit(roles.ADMIN, roles.MANAGER), controller.process('BHARAI'));
router.get('/phukai', permit(roles.ADMIN, roles.MANAGER), controller.process('PHUKAI'));
router.get('/nikasi', permit(roles.ADMIN, roles.MANAGER), controller.process('NIKASI'));
router.get('/chhantai', permit(roles.ADMIN, roles.MANAGER), controller.process('CHHANTAI'));
router.get('/stock', permit(roles.ADMIN, roles.MANAGER), controller.stock);
router.get('/fuel', permit(roles.ADMIN, roles.MANAGER), controller.fuel);
router.get('/worker-ledger', permit(roles.ADMIN, roles.MANAGER), controller.workerLedger);
router.get('/customer-ledger', permit(roles.ADMIN, roles.MANAGER), controller.customerLedger);
router.get('/sales', permit(roles.ADMIN, roles.MANAGER), controller.sales);
router.get('/dispatch', permit(roles.ADMIN, roles.MANAGER), controller.dispatch);
router.get('/expenses', permit(roles.ADMIN, roles.MANAGER), controller.expenses);
router.get('/profit-loss', permit(roles.ADMIN, roles.MANAGER), controller.profitLoss);
module.exports = router;
