const router = require('express').Router();
const { body } = require('express-validator');
const controller = require('./season.controller');
const { protect } = require('../../middlewares/authMiddleware');
const { permit } = require('../../middlewares/roleMiddleware');
const validate = require('../../middlewares/validateRequest');
const roles = require('../../constants/roles');
router.use(protect);
router.get('/', permit(roles.ADMIN, roles.MANAGER), controller.list);
router.post('/', permit(roles.ADMIN), [body('name').notEmpty(), body('startDate').notEmpty()], validate, controller.create);
router.get('/:id', permit(roles.ADMIN, roles.MANAGER), controller.get);
router.patch('/:id', permit(roles.ADMIN), controller.update);
router.patch('/:id/activate', permit(roles.ADMIN), controller.activate);
router.patch('/:id/close', permit(roles.ADMIN), controller.close);
module.exports = router;
