const router = require('express').Router();
const { body } = require('express-validator');
const controller = require('./fuel.controller');
const { protect } = require('../../middlewares/authMiddleware');
const { permit } = require('../../middlewares/roleMiddleware');
const validate = require('../../middlewares/validateRequest');
const roles = require('../../constants/roles');
router.use(protect);
router.get('/types', permit(roles.ADMIN, roles.MANAGER), controller.listTypes);
router.post('/types', permit(roles.ADMIN), [body('code').notEmpty(), body('name').notEmpty()], validate, controller.createType);
router.patch('/types/:id', permit(roles.ADMIN), controller.updateType);
router.get('/stock', permit(roles.ADMIN, roles.MANAGER), controller.stock);
router.get('/purchases', permit(roles.ADMIN, roles.MANAGER), controller.listPurchases);
router.post('/purchases', permit(roles.ADMIN, roles.MANAGER), [body().custom((value) => { if (!value.fuelTypeId && !value.fuelCode) throw new Error('fuelTypeId or fuelCode is required'); return true; }), body('quantity').isNumeric()], validate, controller.createPurchase);
router.get('/consumption', permit(roles.ADMIN, roles.MANAGER), controller.listConsumption);
router.post('/consumption', permit(roles.ADMIN, roles.MANAGER), [body().custom((value) => { if (!value.fuelTypeId && !value.fuelCode) throw new Error('fuelTypeId or fuelCode is required'); return true; }), body('quantity').isNumeric()], validate, controller.createConsumption);
router.get('/reports/consumption', permit(roles.ADMIN, roles.MANAGER), controller.consumptionReport);
router.get('/reports/cost-per-brick', permit(roles.ADMIN, roles.MANAGER), controller.costPerBrick);
module.exports = router;
