module.exports = Object.freeze({
  ATTENDANCE_STATUS: ['PRESENT', 'ABSENT', 'HALF_DAY', 'LATE'],
  SALARY_TYPE: ['DAILY', 'MONTHLY', 'PIECE_RATE'],
  PRODUCTION_TYPE: ['KACCHI_ETH', 'PAKKI_ETH'],
  STOCK_UPDATE_TYPE: ['ADD', 'REDUCE', 'CORRECTION'],
  APPROVAL_STATUS: ['PENDING', 'APPROVED', 'REJECTED'],
  ORDER_STATUS: ['PENDING', 'CONFIRMED', 'LOADING', 'DISPATCHED', 'DELIVERED', 'CANCELLED'],
  PAYMENT_MODE: ['CASH', 'UPI', 'BANK_TRANSFER', 'CHEQUE', 'OTHER'],
  UDHARI_STATUS: ['PENDING', 'PARTIAL_PAID', 'PAID', 'OVERDUE'],
  LEAD_STATUS: ['PENDING', 'DONE', 'MISSED', 'CONVERTED', 'CANCELLED'],
  NOTIFICATION_TYPE: ['PAYMENT_DUE', 'FOLLOW_UP', 'STOCK_APPROVAL', 'ORDER_UPDATE', 'GENERAL'],
  VOICE_RELATED_MODULE: ['ATTENDANCE', 'ORDER', 'PAYMENT', 'WORKER', 'STOCK', 'PRODUCTION', 'LEAD', 'UDHARI']
});
