module.exports = Object.freeze([
  { code: 'ETH_PATHAI', en: 'Eth Pathai / Brick Molding', hi: 'ईंट पथाई' },
  { code: 'RAABIS', en: 'Raabis / Clay Preparation', hi: 'राबिस / मिट्टी तैयारी' },
  { code: 'KACCHA_NIKASI', en: 'Kaccha Nikasi', hi: 'कच्चा निकासी' },
  { code: 'SUKHAI', en: 'Sukhai / Drying', hi: 'सुखाई' },
  { code: 'BHARAI', en: 'Bharai / Kiln Loading', hi: 'भराई' },
  { code: 'PHUKAI', en: 'Phukai / Firing', hi: 'फुकाई' },
  { code: 'PAKAI', en: 'Pakai / Baking', hi: 'पकाई' },
  { code: 'NIKASI', en: 'Nikasi / Unloading', hi: 'निकासी' },
  { code: 'CHHANTAI', en: 'Chhantai / Sorting', hi: 'छंटाई' },
  { code: 'KOYLE', en: 'Koyle Workers', hi: 'कोयला मजदूर' },
  { code: 'COAL_FEEDING', en: 'Coal Feeding Workers', hi: 'कोयला डालने वाले मजदूर' },
  { code: 'LOADING', en: 'Loading Workers', hi: 'लोडिंग मजदूर' },
  { code: 'MITTI_KHUDAI', en: 'Soil Excavation Workers', hi: 'मिट्टी खुदाई मजदूर' },
  { code: 'TRACTOR_DRIVER', en: 'Tractor Driver', hi: 'ट्रैक्टर चालक' },
  { code: 'JCB_OPERATOR', en: 'JCB Operator', hi: 'जेसीबी ऑपरेटर' },
  { code: 'MUNSHI', en: 'Munshi / Supervisor', hi: 'मुंशी / सुपरवाइजर' },
  { code: 'CHOWKIDAR', en: 'Security / Chowkidar', hi: 'चौकीदार' },
  { code: 'ETH_DHULAAI', en: 'Eth Dhulaai Kriya', hi: 'ईंट धुलाई क्रिया' },
  { code: 'OTHER', en: 'Other Labor', hi: 'अन्य मजदूर' }
]);
