const router = require('express').Router();
const { body } = require('express-validator');
const controller = require('./processEntry.controller');
const { protect } = require('../../middlewares/authMiddleware');
const { permit } = require('../../middlewares/roleMiddleware');
const { uploadVoiceNote } = require('../../middlewares/uploadMiddleware');
const validate = require('../../middlewares/validateRequest');
const roles = require('../../constants/roles');
router.use(protect);
router.get('/', permit(roles.ADMIN, roles.MANAGER), controller.list);
router.get('/summary', permit(roles.ADMIN, roles.MANAGER), controller.summary);
router.get('/worker/:workerId', permit(roles.ADMIN, roles.MANAGER), controller.worker);
router.get('/chamber/:chamberId', permit(roles.ADMIN, roles.MANAGER), controller.chamber);
router.post('/', permit(roles.ADMIN, roles.MANAGER), [body('processCode').notEmpty()], validate, controller.create);
router.get('/:id', permit(roles.ADMIN, roles.MANAGER), controller.get);
router.patch('/:id', permit(roles.ADMIN, roles.MANAGER), controller.update);
router.delete('/:id', permit(roles.ADMIN), controller.remove);
router.patch('/:id/approve', permit(roles.ADMIN), controller.approve);
router.patch('/:id/reject', permit(roles.ADMIN), controller.reject);
router.post('/:id/voice-remark', permit(roles.ADMIN, roles.MANAGER), uploadVoiceNote.single('voiceNote'), controller.voiceRemark);
module.exports = router;
