require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const compression = require('compression');
const morgan = require('morgan');
const rateLimit = require('express-rate-limit');
const path = require('path');
const languageMiddleware = require('./middlewares/languageMiddleware');
const { notFound, errorHandler } = require('./middlewares/errorMiddleware');
const routes = require('./routes');
const app = express();
const corsOrigins = (process.env.CORS_ORIGIN || '*').split(',').map((x) => x.trim()).filter(Boolean);
app.use(helmet({ crossOriginResourcePolicy: false }));
app.use(compression());
app.use(cors({ origin: corsOrigins.includes('*') ? '*' : corsOrigins, credentials: true }));
app.use(express.json({ limit: '5mb' }));
app.use(express.urlencoded({ extended: true, limit: '5mb' }));
app.use(languageMiddleware);
if (process.env.NODE_ENV !== 'test') app.use(morgan('dev'));
app.use(rateLimit({ windowMs: Number(process.env.RATE_LIMIT_WINDOW_MS || 900000), max: Number(process.env.RATE_LIMIT_MAX || 300), standardHeaders: true, legacyHeaders: false }));
app.get('/health', (req, res) => res.json({ success: true, message: 'API healthy' }));
app.use('/uploads', express.static(path.resolve(process.cwd(), process.env.UPLOAD_DIR || 'uploads')));
app.use(process.env.API_PREFIX || '/api/v1', routes);
app.use(notFound);
app.use(errorHandler);
module.exports = app;
