const router = require('express').Router();
router.use('/auth', require('./modules/auth/auth.routes'));
router.use('/users', require('./modules/users/user.routes'));
router.use('/kilns', require('./modules/kilns/kiln.routes'));
router.use('/workers', require('./modules/workers/worker.routes'));
router.use('/attendance', require('./modules/attendance/attendance.routes'));
router.use('/production', require('./modules/production/production.routes'));
router.use('/stock', require('./modules/stock/stock.routes'));
router.use('/villages', require('./modules/customers/village.routes'));
router.use('/customers', require('./modules/customers/customer.routes'));
router.use('/orders', require('./modules/orders/order.routes'));
router.use('/udhari', require('./modules/udhari/udhari.routes'));
router.use('/payments', require('./modules/payments/payment.routes'));
router.use('/leads', require('./modules/leads/lead.routes'));
router.use('/voice-remarks', require('./modules/voiceRemarks/voiceRemark.routes'));
router.use('/notifications', require('./modules/notifications/notification.routes'));
router.use('/dashboard', require('./modules/dashboard/dashboard.routes'));
router.use('/logs', require('./modules/logs/activityLog.routes'));
router.use('/constants', require('./modules/constants/constants.routes'));
module.exports = router;
